## Numpy 

In [2]:
import numpy as np

### indexing

In [5]:
array_a = np.array([[2,3,5],[1,4,2]])
array_a

array([[2, 3, 5],
       [1, 4, 2]])

In [4]:
type(array_a)

numpy.ndarray

In [6]:
array_a[0]

array([2, 3, 5])

In [7]:
array_a[0][2]

5

In [8]:
array_a[1][2]

2

In [10]:
array_a[:,1:]

array([[3, 5],
       [4, 2]])

In [11]:
array_a[-1]

array([1, 4, 2])

In [12]:
array_a[0,1]= 4

In [13]:
array_a

array([[2, 4, 5],
       [1, 4, 2]])

In [14]:
array_a[0]=4

In [15]:
array_a

array([[4, 4, 4],
       [1, 4, 2]])

In [16]:
array_a[:,0 ]=10

In [17]:
array_a

array([[10,  4,  4],
       [10,  4,  2]])

## Supported data types

In [7]:
import numpy as np

In [8]:
array_b = np.array([[1,2,4],[4,5,7]], dtype='float')
array_b

array([[1., 2., 4.],
       [4., 5., 7.]])

In [9]:
array_b = np.array([[1,2,4],[4,5,7]], dtype=np.float16)
array_b

array([[1., 2., 4.],
       [4., 5., 7.]], dtype=float16)

In [11]:
array_b = np.array([[1,2,4],[4,5,7]], dtype=np.complex64)
array_b

array([[1.+0.j, 2.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j, 7.+0.j]], dtype=complex64)

In [12]:
array_b = np.array([[1,2,4],[4,5,7]], dtype=np.bool)
array_b

array([[ True,  True,  True],
       [ True,  True,  True]])

In [13]:
array_b = np.array([[1,2,4],[4,5,7]], dtype=np.str)
array_b

array([['1', '2', '4'],
       ['4', '5', '7']], dtype='<U1')

## Broadcasting

Broadcasting rules > 
The arrays have the same shape. 
The arrays have the same number of dimensions , and the length of each dimension is either common or 1.
The arrays that have too few dimension can have their shapes altered with a dimension 1, to satisfy the second rule.

In [14]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [15]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [16]:
matrix_c = np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.add(array_a,matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [18]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

### Type casting

In [20]:
np.add(array_b, matrix_c , dtype=np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

In [21]:
np.add(array_b, matrix_c , dtype=np.str)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U'), dtype('<U')) -> dtype('<U')

### Running over an Axis

In [25]:
np.mean(matrix_c,axis=0)  # axis = 0 , finding the mean for each column of the array

array([2.5, 3.5, 4.5])

In [23]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.mean(matrix_c,axis=1)  # axis = 1 , finding the mean for each row of the array

array([2., 5.])

### ndarrays

In [27]:
#  ndarray = N-Dimensional array
# N > Natural Numbers 

array_a = np.array([1,2,3])

In [28]:
array_a

array([1, 2, 3])

In [29]:
type(array_a)

numpy.ndarray

In [30]:
print(array_a)

[1 2 3]


In [31]:
array_a.shape

(3,)

In [33]:
array_b = np.array([[7,8,9],[10,11,12]])
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [34]:
array_b.shape

(2, 3)

In [35]:
type(array_b)

numpy.ndarray

In [36]:
print(array_b)

[[ 7  8  9]
 [10 11 12]]


In [37]:
array_c = np.array(13)

In [38]:
type(array_c)

numpy.ndarray

In [39]:
print(array_c)

13


In [40]:
array_c.shape

()

In [41]:
array_d = np.array([13])


In [42]:
type(array_d)

numpy.ndarray

In [43]:
array_d.shape

(1,)

In [44]:
print(array_d)

[13]


### List vs Array

In [45]:
list_a = [1,2,4,5,6,7]

In [46]:
len(list_a)

6

In [47]:
list_a = [[1,2,4],[5,6,7]]


In [48]:
len(list_a)

2

In [50]:
type(list_a)

list

In [51]:
array_a = np.array(list_a)

In [52]:
array_a

array([[1, 2, 4],
       [5, 6, 7]])

In [53]:
type(array_a)

numpy.ndarray

In [54]:
print(list_a)

[[1, 2, 4], [5, 6, 7]]


In [55]:
print(array_a)

[[1 2 4]
 [5 6 7]]


In [56]:
# List have len() ## Array have shape
array_a.shape

(2, 3)

In [57]:
list_a.shape

AttributeError: 'list' object has no attribute 'shape'

In [59]:
len(list_a)

2

In [62]:
list_b = list_a[0] + list_a[1]
array_b = array_a[0]+array_a[1]

In [63]:
print(list_b)

[1, 2, 4, 5, 6, 7]


In [64]:
print(array_b)

[ 6  8 11]


In [65]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 2.        ],
       [2.23606798, 2.44948974, 2.64575131]])

### String vs Object vs Numbers